name: "Close asana tasks"
description: "Close asana tasks when the commit message contains the task id"
branding:
  icon: "activity"
  color: "blue"
inputs:
  asana-pat:
    description: "Asana Public Access Token."
    required: true
runs:
  using: "node20"
  main: "action.js"
